### ISSUE TITLE
Streams won't open

### ISSUE THREAD

**Issue by theelichtje** [bbsan2k/plugin.video.f1tv#15]
First off, thanks to both bbsan and TheDevFreak for updating the addon and fork over the last hour, but i still can't get mine to work in 2020. Worked like a treat in 2019, but i can't watch pre-season testing on my HTPC running on LibreElec 9.2.0 with Kodi 18.5. Also won't work on my laptop with Kodi 18.4. I've tested watching old races, but these give the same error as below, so it's not only the 2020 pre-season testing. 

Error log:

2020-02-19 10:02:14.340 T:7780   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.f1tv\main.py", line 14, in <module>
                                                plugin.run()
                                              File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 567, in run
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 529, in router
                                                list_content(params['session_url'], params['session_name'])
                                              File "C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 377, in list_content
                                                for channel in session['channel_urls']:
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
2020-02-19 10:02:14.341 T:7780   DEBUG: CPythonInvoker::onExecutionDone(7, C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.video.f1tv\main.py)
2020-02-19 10:02:14.347 T:7844   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-02-19 10:02:14.385 T:7780    INFO: Python interpreter stopped
2020-02-19 10:02:14.385 T:7780   DEBUG: Thread LanguageInvoker 7780 terminating
2020-02-19 10:02:14.388 T:2704   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.f1tv/?action=list_content&session_name=2020%20Pre-Season%20Testing%202020%20Formula%201%20High%20Speed%20Test&session_url=%2fapi%2fsession-occurrence%2fsess_7b0ceaced4c94e50941b2afbda3c19e3%2f
2020-02-19 10:02:14.388 T:2704   DEBUG: Thread waiting 2704 terminating
2020-02-19 10:02:14.394 T:7844   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-02-19 10:02:14.397 T:7844   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/?action=list_content&session_name=2020%20Pre-Season%20Testing%202020%20Formula%201%20High%20Speed%20Test&session_url=%2fapi%2fsession-occurrence%2fsess_7b0ceaced4c94e50941b2afbda3c19e3%2f) failed

**Comment by TheDevFreak** [comment]
Use discussion in #14
